# -*- coding: utf-8 -*-
"""AML multimodal exercise DOCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW6a47ouftTLKGS7at5Hoc4sT3ir8Szs

#  Document Visual Question Answering (DocVQA)

Input:

    * Document image: A scanned or digital image of a document, containing text, layout, and visual elements.
    * Question about the document: A natural language question posed in text format.

Task:

    * Analyze and understand: The DocVQA model must process both the visual and textual information within the document to fully comprehend its content.
    * Reason and infer: The model needs to establish relationships between visual elements, text, and the question to draw relevant conclusions.
    * Generate a natural language answer: The model must produce a clear, concise, and accurate answer to the question in natural language text format. See the above example for the reference.

Output:

    * Answer to the question: A text response that directly addresses the query and accurately reflects the information found in the document.
"""

!sudo apt install tesseract-ocr libtesseract-dev
!pip -q install pytesseract

import pytesseract

from PIL import Image
import requests

question = "What is the purchase amount?"
url =  "https://www.inv24.com/components/Misc/download/templates/en/images/purchase_invoice_template_xls-1596.jpg"
image = Image.open(requests.get(url, stream=True).raw)

from transformers import pipeline


pipe = pipeline("document-question-answering", model="impira/layoutlm-document-qa")# requires tesseract



out = pipe(image=image, question=question)

import matplotlib.pyplot as plt
import numpy as np
plt.imshow(np.asarray(image))
out

pipe_dounout = pipeline(
    "document-question-answering", model="naver-clova-ix/donut-base-finetuned-docvqa"
)



out = pipe_dounout(image=image, question=question)

out

