# -*- coding: utf-8 -*-
"""AML multimodal Exercises CLIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1UNc_JF1DV-cerbWFZGyftuEAKsDt22

# CLIP
CLIP is a neural network adept at grasping visual concepts through natural language supervision. It operates by concurrently training a text encoder and an image encoder, focusing on a pretraining task that involves matching captions with corresponding images. This architecture allows CLIP to adapt to a variety of visual classification benchmarks seamlessly. It does so by simply receiving the names of the visual categories to be recognized, demonstrating “zero-shot” learning capabilities
"""

from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
caption_list = ["a photo of a cat", "a photo of a dog"]
inputs = processor(
    text=caption_list,
    images=image,
    return_tensors="pt",
    padding=True,
)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

# this is input format, see the tokenization of multimodal input
inputs.keys()

probs

import matplotlib.pyplot as plt
import numpy as np
plt.imshow(np.asarray(image))
#nice formatting
for i,s in enumerate(caption_list):
 print(s, round(probs[0,i].item(),2))

#comprension is quite high, probability are normalized.
#If a more "fitting" alternative is presented, the model shift the weigth in favour of the more detailed description

url = "https://5.imimg.com/data5/DJ/PV/GLADMIN-64970456/computer-lab-class.png"

image = Image.open(requests.get(url, stream=True).raw)
caption_list = ["a computer lab", "a classroom", "a strip club"]
inputs = processor(
    text=caption_list,
    images=image,
    return_tensors="pt",
    padding=True,
)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

plt.imshow(np.asarray(image))
#nice formatting
for i,s in enumerate(caption_list):
 print(s, round(probs[0,i].item(),2))

caption_list = [ "a computer lab","two lines of students sitted with computers","two lines of students","sitted with computers"]
inputs = processor(
    text=caption_list,
    images=image,
    return_tensors="pt",
    padding=True,
)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

plt.imshow(np.asarray(image))
#nice formatting
for i,s in enumerate(caption_list):
 print(s, round(probs[0,i].item(),2))

caption_list = ["two lines of students sitted with computers", "two lines of asian students sitted with computers","two lines of black students sitted with computers","two lines of indian students sitted with computers"]
inputs = processor(
    text=caption_list,
    images=image,
    return_tensors="pt",
    padding=True,
)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

plt.imshow(np.asarray(image))
#nice formatting
for i,s in enumerate(caption_list):
 print(s, round(probs[0,i].item(),2))

