# -*- coding: utf-8 -*-
"""AML multimodal BLIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v72XS_Ebbgoaywu8VWDzSpvFuhcGycGd

## BLIP Image Captioning

**BLIP** stands for **Bootstrapping Language-Image Pre-training**. It is a vision-language model designed for tasks such as image captioning, image-text retrieval, and visual question answering.



This is the large BLIP image-captioning model. It uses a **Vision Transformer (ViT-L)** as the visual backbone and a text-generation module to produce captions from images.

The basic idea is:

1. An image is passed through a vision encoder.
2. The image is converted into visual embeddings.
3. A text decoder generates a caption conditioned on those visual embeddings.
4. The output is decoded into natural language.

In this example, we use the model in two ways:

- **Conditional image captioning**: we provide a text prompt such as `"a photography of"` and ask the model to complete the caption.
- **Unconditional image captioning**: we provide only the image and let the model generate a caption freely.



The **processor** prepares the input for the model. It performs operations such as image resizing, normalization, and text tokenization.

The **model** receives the processed image and optional text prompt, then generates a caption.

---


The image is downloaded from a URL and converted to RGB format.

The `.convert("RGB")` step is important because image-captioning models usually expect three-channel RGB images.

---

## Conditional image captioning

```python
text = "a photography of"

inputs = processor(raw_image, text, return_tensors="pt")

out = model.generate(**inputs)

print(processor.decode(out[0], skip_special_tokens=True))
```

In **conditional captioning**, we provide both:

- the image
- a partial text prompt

Here, the prompt is:

```python
"a photography of"
```

The model generates a caption that continues this prompt.

Conceptually, the model is solving:

```text
Given this image and the prompt "a photography of", generate the most likely continuation.
```

For example, the output may be similar to:

```text
a photography of a woman and her dog on the beach
```

The exact output may vary depending on the model version and generation settings.

---

## Unconditional image captioning

```python
inputs = processor(raw_image, return_tensors="pt")

out = model.generate(**inputs)

print(processor.decode(out[0], skip_special_tokens=True))
```

In **unconditional captioning**, we provide only the image.

The model generates a caption without being guided by an initial text prompt.

Conceptually, the model is solving:

```text
Given this image, describe it in natural language.
```

For example, the output may be similar to:

```text
a woman sitting on the beach with a dog
```

---
"""

import requests
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large"
)

img_url = "https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg"
raw_image = Image.open(requests.get(img_url, stream=True).raw).convert("RGB")

# conditional image captioning
text = "a photography of"
inputs = processor(raw_image, text, return_tensors="pt")

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))

# unconditional image captioning
inputs = processor(raw_image, return_tensors="pt")

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))

